---

- name: Specify MySQL root password before installing
  debconf: name='mysql-server' question='percona-server-server/root-pass' value='root' vtype='password'
  become: true

- name: Confirm MySQL root password before installing
  debconf: name='mysql-server' question='percona-server-server/re-root-pass' value='root' vtype='password'
  become: true

- name: Install packages for PS 
  apt:
    state: latest
    name: "{{ item.value }}"
    update_cache: yes 
  with_items:
          - value: percona-server-server

- name: copy the configuration template
  template:
    src: templates/my.cnf.j2
    dest: /etc/mysql/my.cnf
    owner: root
    group: root
    mode: 0644
  register: mysql_config

- name: restart MySQL if config changed
  systemd:
          name: mysql
          state: restarted
  when: mysql_config.changed

- name: Copy the .my.cnf file for the ubuntu user
  copy:
          src: .my.cnf
          dest: /home/ubuntu/.my.cnf
          owner: ubuntu
          group: ubuntu

- name: copy the user creation script 
  template:
    src: templates/create_user.sh.j2
    dest: /tmp/create_user.sh
    owner: root
    group: root
    mode: 0700

- name: Call the user creation script
  shell: bash /tmp/create_user.sh 

- name: install pmm2-client
  apt:
    state: present 
    name: pmm2-client
  register: aptpmmclientout

- name: connect pmm2-client to server
  shell: "pmm-admin config --server-insecure-tls --server-url=https://admin:admin@{{ groups['mysql'] | map('extract', hostvars, ['ansible_default_ipv4','address']) | first }}"
  when: aptpmmclientout.changed

- name: Add the MySQL metrics
  shell: pmm-admin add mysql --username=root --password=root --query-source=perfschema
  when: aptpmmclientout.changed

