---

- name: copy the installation script 
  copy:
    src: files/get-pmm.sh
    dest: /tmp/get-pmm.sh
    owner: root
    group: root
    mode: 0700

- name: Call installation script
  shell: bash /tmp/get-pmm.sh

- name: Enable the pt repository
  shell: percona-release enable sysbench

- name: Install sysbench
  apt:
    name: sysbench 
    state: latest
    update_cache: yes

- name: Install ps client 
  apt:
    name: percona-server-client
    state: latest

- name: install pmm2-client
  apt:
    state: present
    name: pmm2-client
  register: aptpmmclientout

- name: connect pmm2-client to server
  shell: "pmm-admin config --server-insecure-tls --server-url=https://admin:admin@{{ groups['mysql'] | map('extract', hostvars, ['ansible_default_ipv4','address']) | first }}"
  ignore_errors: yes
  when: aptpmmclientout.changed

- name: copy the configuration template
  template:
    src: templates/prepare.sh.j2
    dest: /home/ubuntu/prepare.sh
    owner: ubuntu
    group: ubuntu
    mode: 0755

- name: copy the configuration template
  template:
    src: templates/run_bench.sh.j2
    dest: /home/ubuntu/run_bench.sh
    owner: ubuntu
    group: ubuntu
    mode: 0755
